services:
  db:
    image: mysql:latest
    container_name: desdai3_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: f1n1shl1n3
      MYSQL_DATABASE: DESDAI3
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
