services:
  postgres_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: insurance_ai
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 10s
      retries: 5
      start_period: 30s

  django_app:
    build: .  # Build the Django app from the Dockerfile
    container_name: desd-aai-y3-group10-django_app-1
    depends_on:
      postgres_db:
        condition: service_healthy  # ✅ Wait for PostgreSQL to be ready
    volumes:
      - .:/app  # ✅ Ensures the local code is reflected in the container
    ports:
      - "8000:8000"  # ✅ Ensure Django is accessible
    environment:
      - DJANGO_SETTINGS_MODULE=insurance_ai.settings
      - DATABASE_NAME=insurance_ai
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=postgres_db  # ✅ Updated to PostgreSQL service name
      - DATABASE_PORT=5432  # ✅ Updated to PostgreSQL port
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
