# Generated by Django 5.1.7 on 2025-05-02 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='accident_description',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='accident_type',
            field=models.CharField(choices=[('Rear end', 'Rear end'), ('Other side pulled out of side road', 'Other side pulled out of side road'), ('Other side pulled on to roundabout', 'Other side pulled on to roundabout'), ("Other side reversed into Clt's vehicle", "Other side reversed into Clt's vehicle"), ("Other side changed lanes and collided with clt's vehicle", "Other side changed lanes and collided with clt's vehicle"), ('Unknown', 'Unknown')], default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='accident',
            name='weather_conditions',
            field=models.CharField(choices=[('Sunny', 'Sunny'), ('Rainy', 'Rainy'), ('Snowy', 'Snowy'), ('Unknown', 'Unknown')], default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='driver',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10),
        ),
        migrations.AlterField(
            model_name='injury',
            name='dominant_injury',
            field=models.CharField(choices=[('Legs', 'Legs'), ('Arms', 'Arms'), ('Hips', 'Hips'), ('Multiple', 'Multiple'), ('Unknown', 'Unknown')], default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='injury',
            name='injury_description',
            field=models.CharField(choices=[('Whiplash and minor bruises', 'Whiplash and minor bruises'), ('Concussion and bruised ribs', 'Concussion and bruised ribs'), ('Minor cuts and scrapes', 'Minor cuts and scrapes'), ('Fractured arm and leg', 'Fractured arm and leg'), ('Sprained ankle and wrist', 'Sprained ankle and wrist'), ('Unknown', 'Unknown')], default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='injury',
            name='injury_prognosis',
            field=models.IntegerField(default=1, help_text='Prognosis in months (whole number, must be at least 1)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='number_of_passengers',
            field=models.IntegerField(default=1, help_text='Number of passengers must be at least 1', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('Motorcycle', 'Motorcycle'), ('Car', 'Car'), ('Truck', 'Truck'), ('Unknown', 'Unknown')], default='Unknown', max_length=255),
        ),
    ]
