# Generated by Django 5.1.7 on 2025-03-12 12:10

import django.db.models.deletion
import django.template.defaulttags
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_date', models.DateTimeField(default=django.template.defaulttags.now)),
                ('accident_type', models.CharField(max_length=255)),
                ('accident_description', models.TextField(blank=True, null=True)),
                ('police_report_filed', models.BooleanField(default=False)),
                ('witness_present', models.BooleanField(default=False)),
                ('weather_conditions', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_date', models.DateTimeField(default=django.template.defaulttags.now)),
                ('settlement_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('special_health_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('special_reduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('special_overage', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('general_rest', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('special_additional_injury', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('special_earnings_loss', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('special_usage_loss', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('special_medications', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('special_asset_damage', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('special_rehabilitation', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('special_fixes', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('general_fixed', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('general_uplift', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('special_loaner_vehicle', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('special_trip_costs', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('special_journey_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('special_therapy', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('accident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='claims.accident')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_age', models.IntegerField(default=18)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('accident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='claims.accident')),
            ],
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_prognosis', models.CharField(blank=True, max_length=255, null=True)),
                ('injury_description', models.TextField(blank=True, null=True)),
                ('dominant_injury', models.CharField(blank=True, max_length=255, null=True)),
                ('whiplash', models.BooleanField(default=False)),
                ('minor_psychological_injury', models.BooleanField(default=False)),
                ('exceptional_circumstances', models.BooleanField(default=False)),
                ('accident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='claims.accident')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_age', models.IntegerField(default=0)),
                ('vehicle_type', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_passengers', models.IntegerField(default=0)),
                ('accident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='claims.accident')),
            ],
        ),
    ]
