# Generated by Django 5.1.7 on 2025-04-28 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_claim_prediction_result'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='CustomUser',
                ),
            ],
            database_operations=[],
        )
    ]
