# Generated by Django 5.1.7 on 2025-03-19 18:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_accident_alter_customuser_managers_claim_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accident',
            name='accident_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
