"""
Django settings for insurance_ai project.

Generated by 'django-admin startproject' using Django 5.1.7.
For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url  # Added for simplified database config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent  # Ensure BASE_DIR is defined first
# Quick-start development settings – unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6tqf65q(u2=35tx_+x214$ug$bdqt08i#+yvi$+jt*+3c($p-j'
# SECRET_KEY = 'django-insecure-!5v-o$66xryd1g$&2a84-x4()*6sbn8=(0rjp*cm3j9pf9fv+t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', 'backend', 'frontend', '127.0.0.1']

# ------------------------------------------------------------------
# Application definition
# ------------------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'authentication.apps.AuthenticationConfig',   # CustomUser lives here
    'claims.apps.ClaimsConfig',
    'health_check',           
    'health_check.db',        
    'health_check.cache', 
    'health_check.storage',
    'engineer.apps.EngineerConfig',
    'finance.apps.FinanceConfig',
    'sysadmin.apps.SysadminConfig',
    'rest_framework',
    'ml_api',  # MLaaS API
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'insurance_ai.middleware.custom_middleware.InactivityLogoutMiddleware',
]

ROOT_URLCONF = 'insurance_ai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'insurance_ai.wsgi.application'

# ------------------------------------------------------------------
# Database
# ------------------------------------------------------------------
DATABASES = {
    'default': dj_database_url.config(
        default=f"postgres://{os.getenv('DATABASE_USER')}:{os.getenv('DATABASE_PASSWORD')}@"
                f"{os.getenv('DATABASE_HOST')}:{os.getenv('DATABASE_PORT')}/"
                f"{os.getenv('DATABASE_NAME')}"
    )
}

# ------------------------------------------------------------------
# Password validation
# ------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ------------------------------------------------------------------
# Internationalization
# ------------------------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ------------------------------------------------------------------
# Static files
# ------------------------------------------------------------------
STATIC_URL = '/static/'
# STATICFILES_DIRS = [BASE_DIR / 'staticfiles']
# STATIC_ROOT = BASE_DIR / 'static'
STATIC_ROOT = '/app/staticfiles'

# ------------------------------------------------------------------
# Default primary-key field type
# ------------------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ------------------------------------------------------------------
# Custom user model
# ------------------------------------------------------------------
AUTH_USER_MODEL = 'authentication.CustomUser'

# ------------------------------------------------------------------
# Authentication / session settings
# ------------------------------------------------------------------
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'role_redirect'
LOGOUT_REDIRECT_URL = 'login'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 660  # 10 hours

# ------------------------------------------------------------------
# CSRF trusted origins
# ------------------------------------------------------------------
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8080",
    "http://frontend:8080",
    "http://127.0.0.1:8080",
    "https://insurance_ai.domain",  # Production URL (certificate + domain needed)
]

# ------------------------------------------------------------------
# MLaaS Configuration
# ------------------------------------------------------------------
MLAAS_SERVICE_URL = os.getenv('MLAAS_SERVICE_URL', 'http://mlaas:8009/api')
DEFAULT_ML_ALGORITHM_ID = int(os.getenv('DEFAULT_ML_ALGORITHM_ID', '1'))
