version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: desdai3_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: f1n1shl1n3
      MYSQL_DATABASE: DESDAI3
      MYSQL_USER: desdai_user
      MYSQL_PASSWORD: f1n1shl1n3
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: desdai3_django
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=DESDAI3
      - DATABASE_USER=desdai_user
      - DATABASE_PASSWORD=f1n1shl1n3
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  mysql_data:
