# Generated by Django 5.1.6 on 2025-03-02 20:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desdai3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accident',
            old_name='location',
            new_name='accident_type',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='date',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='vehicles_involved',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='amount_claimed',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='claimant_name',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='status',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='age',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='name',
        ),
        migrations.RemoveField(
            model_name='injury',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='injury',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='license_plate',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='make',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='model',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='year',
        ),
        migrations.AddField(
            model_name='accident',
            name='accident_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='accident',
            name='accident_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accident',
            name='police_report_filed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accident',
            name='weather_conditions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accident',
            name='witness_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='claim',
            name='general_fixed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='general_rest',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='general_uplift',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='settlement_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='special_additional_injury',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='special_asset_damage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='special_earnings_loss',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='special_fixes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='special_health_expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='special_journey_expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='special_loaner_vehicle',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='special_medications',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='special_overage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='special_reduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='special_rehabilitation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='special_therapy',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='special_trip_costs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='special_usage_loss',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='driver',
            name='accident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='desdai3.accident'),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='driver',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='injury',
            name='dominant_injury',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='injury',
            name='exceptional_circumstances',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='injury',
            name='injury_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='injury',
            name='injury_prognosis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='injury',
            name='minor_psychological_injury',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='injury',
            name='whiplash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='accident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='desdai3.accident'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='number_of_passengers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='accident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='desdai3.accident'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='injury',
            name='accident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='desdai3.accident'),
        ),
        migrations.AlterField(
            model_name='injury',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
