name: Jira Automation
on:
  push:
    branches:
      - main

jobs:
  update_jira:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug Environment Variables (Safe Output)
        run: |
          echo "Checking Jira Environment Variables..."
          echo "JIRA_BASE_URL is set"
          echo "JIRA_USER is set"
          echo "JIRA API Token is set"

      - name: Authenticate with Jira (Avoid Config File Issue)
        uses: atlassian/gajira-login@v3
        with:
          site: ${{ secrets.JIRA_BASE_URL }}
          email: ${{ secrets.JIRA_USER }}
          api-token: ${{ secrets.JIRA_API_TOKEN }}

      - name: Jira Integration - Create Issue
        uses: atlassian/gajira-create@v3
        with:
          project: "SCRUM"
          issuetype: "Task"
          summary: "New commit pushed to main"
          description: "A new commit has been made to the repository and should be tracked in Jira."

