name: Jira Automation
on:
  push:
    branches:
      - main

jobs:
  update_jira:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Jira Integration - Create Issue
        uses: atlassian/gajira-create@v3
        with:
          project: "DESD"  # Replace with your actual Jira project key
          issuetype: "Task"
          summary: "New commit pushed to main"
          description: "A new commit has been made to the repository and should be tracked in Jira."
        env:
          JIRA_BASE_URL: "${{ secrets.JIRA_BASE_URL }}"
          JIRA_USER: "${{ secrets.JIRA_USER }}"
          JIRA_API_TOKEN: "${{ secrets.JIRA_API_TOKEN }}"

